import Head from 'next/head'
import React from 'react'

interface Props {
    title: string
}

const PageHead = ({ title }: Props) => {
    return (
        <Head>
            <title>{title}</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
    )
}

export default PageHead