import Head from 'next/head'
import * as Popover from '@radix-ui/react-popover';


export default function Home() {
  return (
    <div className='bg-primary h-screen'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>H1 heading</h1>
      <h2>H2 heading</h2>
      <h3>H3 heading</h3>
      <Popover.Root>
        <Popover.Trigger className="bg-red-300">Show info</Popover.Trigger>
        <Popover.Portal className=''>
          <Popover.Content className="bg-blue-100">
            Some content
            <Popover.Arrow className="border bg-teal-200 text-xl" />
          </Popover.Content>
        </Popover.Portal>
      </Popover.Root>
    </div>
  )
}
